# Generated by Django 2.0.7 on 2018-07-19 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('UW', 'Upper West Region'), ('UE', 'Upper East Region'), ('N', 'Northern Region'), ('BA', 'Brong Ahafo Region'), ('A', 'Ashanti Region'), ('E', 'Eastern Region'), ('W', 'Western Region'), ('V', 'Volta Region'), ('GA', 'Greater Accra Region'), ('C', 'Upper West Region')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('o_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField()),
                ('admin_date', models.DateField()),
                ('grad_date', models.DateField()),
                ('sch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.School')),
            ],
        ),
    ]
